apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-gcs-pvc-dy-key
spec:
  storageClassName: csi-gcs-dy-key
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
