apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gcs-csi
spec:
  selector:
    matchLabels:
      app: gcs-csi
  template:
    metadata:
      labels:
        app: gcs-csi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      tolerations:
      - operator: "Exists"
      hostNetwork: true
      hostPID: true
      initContainers:
        - name: install-csifuse-proxy
          #image: gcs:proxy
          image: gcscsi:v1.0
          imagePullPolicy: IfNotPresent
          command:
            - "/csifuse-proxy/install-csiproxy.sh"
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
          - name: workload-identity-credential-configuration
            mountPath: "/etc/workload-identity"
            readOnly: true
          - name: host-usr
            mountPath: /host/usr
          - name: host-etc
            mountPath: /host/etc
          - name: lib-modules
            mountPath: /lib/modules
            readOnly: true
          - name: proc
            mountPath: /proc
      containers:
      - name: csi-node-driver-registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
        imagePullPolicy: IfNotPresent
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/gcs.csi.shein.dev/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
        - name: registration-dir
          mountPath: /registration
        - name: socket-dir
          mountPath: /csi
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 20Mi
      - name: csi-provisioner
        image: aurora6/csi-provisioner:v2.2.2
        args:
          - "--csi-address=$(ADDRESS)"
          - "--extra-create-metadata"
          - "--leader-election"
          - "--leader-election-namespace=$(NAMESPACE)"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        - name: NAMESPACE
          value: gcs-csi-test
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy/
      - name: gcs-csi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        image: gcscsi:v1.0
        imagePullPolicy: IfNotPresent 
        args:
        - "/usr/local/bin/driver"
        - "--node-name=$(KUBE_NODE_NAME)"
        - "--v=5"
        #- "--delete-orphaned-pods=true"
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: token
          mountPath: "/var/run/service-account"
        - name: mountpoint-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: "Bidirectional"
        - name: socket-dir
          mountPath: /csi
        - name: host-var
          mountPath: /host/var/run/service-account
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: proc
          mountPath: /proc
        - name: plugins-mount-dir
          mountPath: /var/lib/kubelet/plugins
          mountPropagation: "Bidirectional"

        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 80Mi

      serviceAccountName: test-sa
      volumes:
      - name: token
        projected:
          sources:
          - serviceAccountToken:
              audience: https://iam.googleapis.com/projects/362600025029/locations/global/workloadIdentityPools/gcscsi-test/providers/gcscsi-test
              expirationSeconds: 3600
              path: token
      - name: workload-identity-credential-configuration
        configMap:
          name: gcp-cred
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/gcs.csi.shein.dev
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
      - name: mountpoint-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
      - name: plugins-mount-dir
        hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
      - name: host-var
        hostPath:
          path: /var/run/service-account
      - name: host-etc
        hostPath:
          path: /etc
      - name: host-usr
        hostPath:
          path: /usr
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: proc
        hostPath:
          path: /proc

