apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-gcs-pv-key
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-gcs-test-sc-key
  mountOptions:
  - -o=allow_other
  - --gid=0
  - --dir-mode=0775
  - --file-mode=0775
  - --implicit-dirs
  csi:
    driver: gcs.csi.shein.dev
    volumeHandle: csi-gcs-pv-key
    volumeAttributes:
      bucket: gcscsi-test
      #gid: "0"
      #dirMode: "0775"
      #fileMode: "0775"
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: default
